### ISSUE TITLE
Doesn't load module

### ISSUE THREAD

**Issue by ghost** [richorama/literate#1]
I tried using this package in a recent project of mine. [See my project here on github](https://github.com/theonlygusti/befunge/) and see [the issue on that project](https://github.com/theonlygusti/befunge/issues/2) related to this.

When trying to load a markdown file within a subdirectory I get the error:

```
module.js:472
    throw err;
    ^

Error: Cannot find module '../.././versions/Befunge-93'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at parseJS (../node_modules/literate/index.js:30:9)
    at Object.<anonymous> (./befunge.js:2:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

**Comment by richorama** [comment]
This should be fixed now - although I notice that your module needs to attach a function to `module.exports` ;¬)

**Comment by theonlygusti** [comment]
Is this live on npm yet? `npm update literate` does not change anything
