### ISSUE TITLE
your_module.useAsNormal(); is not a function

### ISSUE THREAD

**Issue by ghost** [richorama/literate#2]
Following the example:

```js
var your_module = require('literate')('./your_module');
your_module.useAsNormal();
```

node throws the error

```
your_module.useAsNormal();
        ^

TypeError: your_module.useAsNormal is not a function
    at Object.<anonymous>
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

**Comment by richorama** [comment]
Hi @theonlygusti,

Yet it's published to npm (version 0.0.3).

I don't think your module attaches a function to `module.exports` called `useAsNormal`. Therefore it's giving you the error.

**Comment by ghost** [comment]
Ah right, my understanding of your README was that `useAsNormal` was an initialiser function xD

My bad.

**Comment by richorama** [comment]
Sorry, the readme is a bit confusing! Glad you've got it working :¬)
